<a href="https://colab.research.google.com/github/sadik-tofik/NLP_Assignment/blob/main/NLP_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing (NLP) Assignment
This assignment will guide you through the basic concepts of Natural Language Processing including:
- Text preprocessing
- Tokenization and N-grams
- Named Entity Recognition (NER)
- Converting text into numbers (vectorization)
- Word embeddings (for experienced learners)

You can run and modify the code cells below to complete the tasks.

In [ ]:
# Import required libraries
import nltk
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import numpy as np
import pandas as pd
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import ngrams
nlp = spacy.load("en_core_web_sm")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## 1. Text Preprocessing
Clean the following text by converting it to lowercase, removing punctuation and stop words.

In [13]:


def preprocess(text):
    # Convert to lowercase
    text = text.lower()
    # Tokenize
    tokens = word_tokenize(text)
    # Remove punctuation and stopwords
    stop_words = set(stopwords.words('english'))
    cleaned_tokens = [word for word in tokens if word not in stop_words and word not in string.punctuation]
    return cleaned_tokens

# Define the text to preprocess
text = "Natural Language Processing (NLP) is a fascinating field that combines computer science, artificial intelligence, and linguistics to enable computers to understand and process human language. It has a wide range of applications, including machine translation, sentiment analysis, chatbots, and speech recognition. The process typically involves several steps, starting with text preprocessing, which includes tasks like lowercasing, tokenization, and removing punctuation and stop words. Following preprocessing, techniques like stemming and lemmatization can be applied to reduce words to their root forms. Tokenization breaks down text into individual words or sub-word units, while n-grams capture sequences of these tokens, providing more context. Named Entity Recognition (NER) is another important task in NLP, which identifies and classifies named entities in text, such as people, organizations, and locations. Converting text into numerical representations is crucial for machine learning models, and methods like CountVectorizer and TF-IDF are commonly used for this purpose. More advanced techniques involve word embeddings, which represent words as dense vectors in a continuous vector space, capturing semantic relationships between words."


# Print cleaned tokens
cleaned_tokens = preprocess(text)
print(cleaned_tokens)

['natural', 'language', 'processing', 'nlp', 'fascinating', 'field', 'combines', 'computer', 'science', 'artificial', 'intelligence', 'linguistics', 'enable', 'computers', 'understand', 'process', 'human', 'language', 'wide', 'range', 'applications', 'including', 'machine', 'translation', 'sentiment', 'analysis', 'chatbots', 'speech', 'recognition', 'process', 'typically', 'involves', 'several', 'steps', 'starting', 'text', 'preprocessing', 'includes', 'tasks', 'like', 'lowercasing', 'tokenization', 'removing', 'punctuation', 'stop', 'words', 'following', 'preprocessing', 'techniques', 'like', 'stemming', 'lemmatization', 'applied', 'reduce', 'words', 'root', 'forms', 'tokenization', 'breaks', 'text', 'individual', 'words', 'sub-word', 'units', 'n-grams', 'capture', 'sequences', 'tokens', 'providing', 'context', 'named', 'entity', 'recognition', 'ner', 'another', 'important', 'task', 'nlp', 'identifies', 'classifies', 'named', 'entities', 'text', 'people', 'organizations', 'locations',

## 2. Tokenization and N-grams
Generate bigrams (2-grams) from the cleaned tokens.

In [14]:
# Generate bigrams from cleaned tokens
bigrams = list(ngrams(cleaned_tokens, 3))
print("Bigrams:", bigrams)

Bigrams: [('natural', 'language', 'processing'), ('language', 'processing', 'nlp'), ('processing', 'nlp', 'fascinating'), ('nlp', 'fascinating', 'field'), ('fascinating', 'field', 'combines'), ('field', 'combines', 'computer'), ('combines', 'computer', 'science'), ('computer', 'science', 'artificial'), ('science', 'artificial', 'intelligence'), ('artificial', 'intelligence', 'linguistics'), ('intelligence', 'linguistics', 'enable'), ('linguistics', 'enable', 'computers'), ('enable', 'computers', 'understand'), ('computers', 'understand', 'process'), ('understand', 'process', 'human'), ('process', 'human', 'language'), ('human', 'language', 'wide'), ('language', 'wide', 'range'), ('wide', 'range', 'applications'), ('range', 'applications', 'including'), ('applications', 'including', 'machine'), ('including', 'machine', 'translation'), ('machine', 'translation', 'sentiment'), ('translation', 'sentiment', 'analysis'), ('sentiment', 'analysis', 'chatbots'), ('analysis', 'chatbots', 'speech

## 3. Named Entity Recognition (NER)
Use spaCy to perform NER on a new sentence.

In [15]:
# Example sentence
sentence = "The Google headquarters in Mountain View, California, was founded by Larry Page and Sergey Brin in 1998. Sundar Pichai is the current CEO."
doc = nlp(sentence)
for ent in doc.ents:
    print(ent.text, ent.label_)

Google ORG
Mountain View GPE
California GPE
Larry Page PERSON
Sergey Brin PERSON
1998 DATE
Sundar Pichai PERSON


## 4. Converting Text to Numbers
Use CountVectorizer and TfidfVectorizer to convert a list of sentences into numeric vectors.

In [16]:
sentences = [
    "I love machine learning.",
    "Natural language processing is a part of AI.",
    "AI is the future.",
    "Machine learning is a fascinating field.",
    "NLP helps computers understand human language.",
    "Vectorization is key for text analysis.",
    "TF-IDF gives importance to relevant words."
]

# CountVectorizer
count_vec = CountVectorizer()
X_count = count_vec.fit_transform(sentences)
print("Count Vectorizer Output:\n", X_count.toarray())

# TfidfVectorizer
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(sentences)
print("\nTF-IDF Vectorizer Output:\n", X_tfidf.toarray())

Count Vectorizer Output:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1]]

TF-IDF Vectorizer Output:
 [[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.53828134 0.64846464 0.53828134
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.34594225 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.25672902 0.         0.34594225 0.         0.

## 5. Word Embeddings (Advanced)
Use spaCy to get word vectors (embeddings) for given words.

In [17]:
# Note: en_core_web_sm does not have word vectors. You can install and use en_core_web_md
# Uncomment below to install and load the medium model if needed.
# !python -m spacy download en_core_web_md
# nlp = spacy.load("en_core_web_md")

# Example word vector
word = nlp("machine")[0]
print("Vector for 'machine':\n", word.vector)
# Another example word vector
word_language = nlp("language")[0]
print("Vector for 'language':\n", word_language.vector)

Vector for 'machine':
 [-0.7506131  -0.57648134  0.64351434  0.34771815  0.45008683 -0.31984502
  1.3374304   0.6823808  -0.2497879   0.01502723  0.20069116 -0.53005815
 -0.32142693  0.6083895   0.5911227   1.3969526  -1.3394687  -0.49667895
  0.93146133  0.76211375 -0.63203835  1.1820786  -0.8377956   0.02632815
 -0.2938518   0.6069318   1.5544686  -0.04658484 -0.4521918   0.48126173
  0.02117339  0.9538507   0.38607836  0.03060612 -1.2614324  -0.71200204
 -0.0582068   0.9979756   0.39407492  0.03983042 -0.9099759  -0.30680424
  0.81676024  0.40132928 -0.6591901  -0.52833277 -0.1020698  -0.39648485
 -0.2746659  -0.5868281   0.11670423 -0.02715784  0.10342616 -0.71523666
  0.78196347  0.26182324  1.2007883   0.40819865 -0.81201667  0.10142356
 -0.92464274 -0.0610747  -0.28506368 -0.27212036 -0.06658131  0.21739644
 -0.34570417 -0.7191127  -0.6493219  -0.07578599 -0.26895642  0.25262332
  0.8506174   0.5730195  -0.10925089 -0.48964912 -0.33062595 -0.6904906
  0.58739054  0.52517235 -0.4